template: true
valuesFilePath: ./values.yml

resources:
  - name: upload_artifact_gitrepo_1
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https

pipelines:
  - name: upload_artifact_publish
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u18node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          TASK_NAME: jfrog/upload_artifact
          TASK_VERSION: 0.0.${run_number}
          TASK_REPOSITORY: pipelines-tasks-local
    steps:
      - name: build_and_publish_task
        type: Bash
        configuration:
          inputResources:
            - name: upload_artifact_gitrepo_1
              trigger: false
          integrations:
            - name: {{ .Values.artIntegration }}
        execution:
          onExecute:
            # Make sure version was provided
            - test -n "$TASK_VERSION" -a "$TASK_VERSION" != "0.0.0"
            - jf c show
            # Run publish task
            - task: jfrog/publish-task@v0.1.0
              id: publish_docker_build
              input:
                path: $res_upload_artifact_gitrepo_1_resourcePath
                targetRepository: $TASK_REPOSITORY
                taskName: $TASK_NAME
                taskVersion: $TASK_VERSION
                includePattern: ^README.md$|^dist
      - name: test_published_upload_artifact_task
        type: Bash
        configuration:
          inputResources:
            - name: upload_artifact_gitrepo_1
              trigger: false
          inputSteps:
            - name: build_and_publish_task
          integrations:
            - name: {{ .Values.artIntegration }}
        execution:
          onExecute:
            # Run task
            - task: $TASK_NAME@v$TASK_VERSION
              rtIntegration: {{ .Values.artIntegration }}
              input:
                inputResource: "upload_artifact_gitrepo_1"
                sourcePath: .*
                targetPath: jfrog-pipelines
